### ISSUE TITLE
Not tracing

### ISSUE THREAD

**Issue by tvfoodmaps** [opentracing-contrib/java-spring-rabbitmq#10]
I added the following to my gradle:

`  compile('io.opentracing.contrib:opentracing-spring-rabbitmq-starter:latest.release')`

And my Spring code to send a message is:

```
@Autowired
     public KCSender(RabbitTemplate template, Queue queue) {
         this.template = template;
         this.queue = queue;
     }


      private RabbitTemplate template;


      private Queue queue;

      public void send(String type, String data) {

          if (template == null){
            log.error("template null");
          }
          if (queue==null){
            log.error("queue null");
          }

          RabbitMsg msg = new RabbitMsg(type,data);

          this.template.convertAndSend(queue.getName(), msg);
          log.info(" [x] Sent '" + msg.toString() + "'");
      }
```

Yet nothing n Jaeger (other spans are reported).  Any tips to debug?

**Comment by ask4gilles** [comment]
Hi,
I guess this occurs because the [aspect](https://github.com/opentracing-contrib/java-spring-rabbitmq/blob/master/opentracing-spring-rabbitmq/src/main/java/io/opentracing/contrib/spring/rabbitmq/RabbitMqSendTracingAspect.java) triggers on an other method signature:
`
@Around(value = "execution(* org.springframework.amqp.core.AmqpTemplate.convertAndSend(..)) && args(exchange,"
            + "routingKey, message)", argNames = "pjp,exchange,routingKey,message"
  )
`
ie with exchange, routing key and message. Can you give it a try?

**Comment by tvfoodmaps** [comment]
Hmm, no luck.  Changed code to:

`  this.template.convertAndSend(exchange.getName(),serviceQueue.getName(), msg);
`       
Sam result.

Also of note, when I turn on org.springframework.beans I never see RabbitMqTracingAutoConfiguration bean get loaded (not sure if I should).

**Comment by ask4gilles** [comment]
Can you point me to a sample project on a github repo?

**Comment by ask4gilles** [comment]
Closing in lack of reaction. Reopen and provide and example if needed.
